### ISSUE TITLE
mr can this is a pretty impressive amount of work for a dutch person

### ISSUE THREAD

**Issue by CR3Swapper** [can1357/selene#2]
Unfortunately the CRT is locked away in a license to the watermelon man 🍉 👨 

https://github.com/can1357/selene/blob/e3182ad52333d688d14d48b6181b081ba73e840b/pdblib/includes/pdblib/cvinfo.h

Did the pdb includes come from microsofts public repo for parsing pdb file format? you should isolate this pdb parsing code into its own lib if its not already. Rust has a pretty good pdb parser and i wrote my own to edit pdb files but there isnt a nice one like yours in c++

Anyways good work.

![dog-with-no-enemies](https://github.com/user-attachments/assets/587f6574-2584-4647-a613-4713502f168d)

**Comment by thug-shaker** [comment]
I absolutely loved using CanCRT for my discord token stealer. Incredible technology!
Combining this with the INCREDIBLE vtil deobfuscator.
Turkish retard just can't stop releasing absolute bangers!
Oh my fucking god this shit has his retarded wasm based vm obfuscator as well.
Hope you catch Turkish aids @can1357

**Comment by can1357** [comment]
The contents of the `cv*.h` files are indeed from Ms/PDB, although I belive I have changed a few that was inaccurate or incomplete, not a fun repository to work with.

Very busy with work atm which is why I've published the monorepo as is but I will make them into small modules once I have more free time.
